### ISSUE TITLE
Document ways to use UI5 libraries

### ISSUE THREAD

**Issue by ArnaudBuchholz** [ArnaudBuchholz/ui5-test-runner#84]
Put it as an NPM dependency and refer to it under node_modules

**Comment by metzing** [comment]
Hi @ArnaudBuchholz 

I think this part of the docs is misleading: https://github.com/ArnaudBuchholz/ui5-test-runner/blob/main/docs/configuration.md#configuration-file

It explicitly states that the `libs` parameter should be a split into a key value pair, but when I was doing that I received

```
Error: Unable to access generic lib mapping (/path/to/app/[object Object]), check your settings
    at checkAccess (/path/to/app/node_modules/ui5-test-runner/src/job.js:190:11)
    at /path/to/app/node_modules/ui5-test-runner/src/job.js:270:7
    at Array.forEach (<anonymous>)
    at finalize (/path/to/app/node_modules/ui5-test-runner/src/job.js:262:14)
    at fromCmdLine (/path/to/app/node_modules/ui5-test-runner/src/job.js:372:3)
    at main (/path/to/app/node_modules/ui5-test-runner/index.js:44:9)
    at Object.<anonymous> (/path/to/app/node_modules/ui5-test-runner/index.js:95:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
```

I believe the `lib` validator is not taking respecting the documentation 😅 
https://github.com/ArnaudBuchholz/ui5-test-runner/blob/main/src/job.js#L54

**Comment by ArnaudBuchholz** [comment]
@metzing Thanks for pointing out the issue, I will adjust the documentation.
I am afraid this is an artefact of the v1 mappings that I need to fix.

I need to double check it but I believe the proper syntax would be :
```json
{
  "libs": [
    "my/namespace/feature/lib/=../my.namespace.feature.project.lib/src/my/namespace/feature/lib/"
  ]
}
```
